version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    expose:
      - "8000"
    env_file:
      - ../backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

   nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
