version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

