name: CI Pipeline

on:
  push:
    branches: [main, production]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Test Frontend
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install & Test Backend
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest

      - name: Deploy
        if: github.ref == 'refs/heads/production'
        run: echo "Deployment triggered via Vercel + Render webhooks"

